--Ensayo
SELECT nextval('"CPSAA"."GESAC_SEQ_ID_ENS"') from "CPSAA"."GESAC_SEQ_ID_ENS"

SELECT MAX("SCMOE_IDE_ENSA_K") FROM "CPSAA"."GESAC_MOV_ENSA" 

--Muestra
SELECT nextval('"CPSAA"."GESAC_SEQ_ID_MUE"') from "CPSAA"."GESAC_SEQ_ID_MUE"

SELECT MAX("SCMOM_IDE_MUES_K") FROM "CPSAA"."GESAC_MOV_MUES"

--Unidad de muestra

SELECT nextval('"CPSAA"."GESAC_SEQ_ID_UNI_MUE"') from "CPSAA"."GESAC_SEQ_ID_UNI_MUE"

SELECT MAX("SCMUM_IDE_UNID_MUES") FROM "CPSAA"."GESAC_MOV_UNID_MUES"


