--SE CREA EL PERMISO PARA LA OPCION DE LOTE PNC
INSERT INTO "CPSAA"."GESAC_MAE_PERM"(
            "SCMAP_IDE_PERM_K", "SCMAP_COC_PERM", "SCMAP_NOM_PERM", "SCMAP_GLS_DES", 
            "SCMAP_GLS_MOD_FUN", "SCMAP_GLS_CAS_USO", "SCMAP_COC_EST")
    VALUES ((SELECT coalesce(max(PER."SCMAP_IDE_PERM_K"),0) + 1 FROM "CPSAA"."GESAC_MAE_PERM" PER), 'CAL010_PER_001', 'LOTE PNC - Inicio', 'Permite ingresar a la pantalla principal lote PNC', 
            'CAL', 'CAL010', 'ACT');



-- SE RELACIONA EL PERMISO CON EL ROL
INSERT INTO "CPSAA"."GESAC_DET_PERM_ROL"(
            "SCDPR_IDE_PERM_ROL_K", "SCMAP_IDE_PERM_K", "SCMAR_IDE_ROL_K", 
            "SCDPR_FLG_ELI", "SCDPR_COC_EST")
    VALUES ((SELECT coalesce(max(DET."SCDPR_IDE_PERM_ROL_K"),0) + 1 FROM "CPSAA"."GESAC_DET_PERM_ROL" DET), X, 11, 
            'N', 'ACT');
			
-- DONDE X = EL VALOR DEL SCMAP_IDE_PERM_K DE LA TABLA "CPSAA"."GESAC_MAE_PERM" (DEL REGISTRO QUE SE EJECUTO ANTERIORMENTE)



--SE CREA EL PERMISO PARA LA OPCION DE REGISTRAR LOTE, MUESTRAS, TRAZABILIDAD Y ENSAYOS
  INSERT INTO "CPSAA"."GESAC_MAE_PERM"(
            "SCMAP_IDE_PERM_K", "SCMAP_COC_PERM", "SCMAP_NOM_PERM", "SCMAP_GLS_DES", 
            "SCMAP_GLS_MOD_FUN", "SCMAP_GLS_CAS_USO", "SCMAP_COC_EST")
    VALUES ((SELECT coalesce(max(PER."SCMAP_IDE_PERM_K"),0) + 1 FROM "CPSAA"."GESAC_MAE_PERM" PER), 'CAL009_PER_001', 'Registrar Lote, Muestras, Trazabilidad y Ensayos', 'Permite ingresar a la pantalla de registrar Lote, Muestras, Trazabilidad y Ensayos', 
            'CAL', 'CAL009', 'ACT');


INSERT INTO "CPSAA"."GESAC_DET_PERM_ROL"(
            "SCDPR_IDE_PERM_ROL_K", "SCMAP_IDE_PERM_K", "SCMAR_IDE_ROL_K", 
            "SCDPR_FLG_ELI", "SCDPR_COC_EST")
    VALUES ((SELECT coalesce(max(DET."SCDPR_IDE_PERM_ROL_K"),0) + 1 FROM "CPSAA"."GESAC_DET_PERM_ROL" DET), Y, 11, 
            'N', 'ACT');

-- DONDE Y = EL VALOR DEL SCMAP_IDE_PERM_K DE LA TABLA "CPSAA"."GESAC_MAE_PERM" (DEL REGISTRO QUE SE EJECUTO ANTERIORMENTE)
			

			
-- SE CREA UN NUEVO ROL PARA QUE TENGA ACCESO A TODOS LOS MANTENIMIENTOS DEL ADMINISTRAR DATOS
INSERT INTO "CPSAA"."GESAC_MAE_ROL"("SCMAR_IDE_ROL_K", "SCMAR_NOM_ROL", "SCMAR_GLS_DES", "SCMAR_COC_EST")
    VALUES ((SELECT coalesce(max(ROL."SCMAR_IDE_ROL_K"),0) + 1 FROM "CPSAA"."GESAC_MAE_ROL" ROL), 'Responsable de Administración de Datos', 'Tendrá acceso a todos los mantenimientos del Administrar Datos', 'ACT');

	
	
-- SE CREA UN PERMISO PARA AMARRAR AL ROL CREADO ANTERIORMENTE
INSERT INTO "CPSAA"."GESAC_MAE_PERM"("SCMAP_IDE_PERM_K", "SCMAP_COC_PERM", "SCMAP_NOM_PERM", "SCMAP_GLS_DES", "SCMAP_GLS_MOD_FUN", "SCMAP_GLS_CAS_USO", "SCMAP_COC_EST")
VALUES ((SELECT coalesce(max(PER."SCMAP_IDE_PERM_K"),0) + 1 FROM "CPSAA"."GESAC_MAE_PERM" PER), 'SIS003_PER_002', 'Administrar Datos', 
'Tendrá acceso a todos los mantenimientos del Administrar Datos', 'SIS', 'CAL002', 'ACT');


-- SE RELACIONA EL ROL CON EL PERMISO
INSERT INTO "CPSAA"."GESAC_DET_PERM_ROL"(
            "SCDPR_IDE_PERM_ROL_K", "SCMAP_IDE_PERM_K", "SCMAR_IDE_ROL_K", 
            "SCDPR_FLG_ELI", "SCDPR_COC_EST")
    VALUES ((SELECT coalesce(max(PER."SCDPR_IDE_PERM_ROL_K"),0) + 1 FROM "CPSAA"."GESAC_DET_PERM_ROL" PER), Z, 35, 
            'N', 'ACT');
			

-- DONDE Z = EL VALOR DEL SCMAP_IDE_PERM_K DE LA TABLA "CPSAA"."GESAC_MAE_PERM" (DEL REGISTRO QUE SE EJECUTO ANTERIORMENTE)