INSERT INTO "CPSAA"."GESAC_PAR_SIS"("SCPAS_IDE_PAR_SIS_K", "SCPAS_NOM_PAR", "SCPAS_GLS_DES", "SCPAS_GLS_VLR")
    VALUES ( (SELECT coalesce(max(PAR."SCPAS_IDE_PAR_SIS_K"),0) + 1 FROM "CPSAA"."GESAC_PAR_SIS" PAR), 
    'PARAMETRO_ANIO_REINICIO_ID_LOTE_Y_ENSAYO', 'Anio para reinicio de id de Lote y Ensayo', '2012');



INSERT INTO "CPSAA"."GESAC_PAR_SIS"("SCPAS_IDE_PAR_SIS_K", "SCPAS_NOM_PAR", "SCPAS_GLS_DES", "SCPAS_GLS_VLR")
    VALUES ((SELECT coalesce(max(PAR."SCPAS_IDE_PAR_SIS_K"),0) + 1 FROM "CPSAA"."GESAC_PAR_SIS" PAR), 
	'PARAMETRO_NUMERO_TURNOS_ADICIONALES', 'Numero de turnos a aumentar en la pantalla de Administrar Turnos', '5');